apiVersion: v2
type: application
name: opencloud-dev
version: 0.1.0
description: "DEV Deployment of the OpenCloud dockerfile. The DEV Helm chart follows the description given for starting a docker instance: https://docs.opencloud.eu/docs/admin/getting-started/docker. It is not thought for productive use"
home: https://github.com/opencloud-eu/helm
image: https://raw.githubusercontent.com/opencloud-eu/opencloud/refs/heads/main/opencloud_logo.png
sources:
- https://github.com/opencloud-eu/helm
appVersion: 2.0.0
