# follow the description given for starting a docker instance 
# https://docs.opencloud.eu/docs/admin/getting-started/docker

image: opencloudeu/opencloud-rolling
tag: 2.0.0

adminPassword: admin
insecure: true
proxyHttpAddr: 0.0.0.0:9200
url: https://localhost:9200

pvcSize: 10Gi

  