{{- if and (not .Values.opencloud.storage.s3.internal.existingSecret) .Values.opencloud.storage.s3.internal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: minio
type: Opaque
stringData:
  rootUser: {{ .Values.opencloud.storage.s3.internal.rootUser }}
  rootPassword: {{ .Values.opencloud.storage.s3.internal.rootPassword }}
{{- end }}