# helmfile.yaml for OpenCloud Full Deployment
# This file organizes the deployment of OpenCloud and its dependencies using Helmfile.

# --- Repositories ---
# Define Helm chart repositories used in this deployment.
repositories:
  - name: openldap
    url: https://jp-gouin.github.io/helm-openldap/

# --- Releases ---
# Define the Helm chart releases to be deployed.

releases:
  # --- OpenCloud Microservice Chart Release ---
  # Deploys the main OpenCloud application with all its integrated services.
  - name: opencloud-helm
    namespace: opencloud-helm # Dedicated namespace for the OpenCloud deployment.
    chart: ../../ # Path to the OpenCloud Helm chart.
    values:
      # --- General Settings ---
      - logging:
          level: debug # Set logging level for OpenCloud components.
      - externalDomain: cloud.opencloud.test # Main domain for OpenCloud access.

      # --- Core Components Configuration ---
      - keycloak:
          enabled: true # Enable Keycloak for authentication.
          domain: keycloak.opencloud.test # Domain for Keycloak.
      - minio:
          enabled: true # Enable MinIO for object storage.
          domain: minio.opencloud.test # Domain for MinIO.
          config:
            persistence:
              size: "40Gi"
      - onlyoffice:
          enabled: false
          domain: onlyoffice.opencloud.test # Domain for OnlyOffice.
          persistence:
            size: "2Gi" # Added

      - collabora:
          enabled: true
          domain: collabora.opencloud.test # Domain for Collabora.

      # --- Networking Configuration ---
      - ingress:
          enabled: false # Disable traditional Ingress as Gateway API is used.
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m # Max body size for NGINX ingress.
      - insecure:
          oidcIdpInsecure: true
          ocHttpApiInsecure: true
      - secretRefs:
          ldapSecretRef: ldap-bind-secrets # we provide the ldap bind password of the ldap server in the extraResources section as secret
          s3CredentialsSecretRef: s3secret
      - gateway:
          httproute:
            enabled: true
      - features:
          externalUserManagement:
            enabled: true
            adminUUID: "0ab77e6d-23b4-4ba3-9843-a3b3efdcfc53"
            autoprovisionAccounts:
              enabled: true
              claimUserName: sub
            oidc:
              domain: keycloak.opencloud.test
              issuerURI: https://keycloak.opencloud.test/realms/openCloud
              userIDClaim: sub
              userIDClaimAttributeMapping: username
              roleAssignment:
                claim: roles
            ldap:
              writeable: true
              uri: ldaps://openldap.openldap.svc.cluster.local:636
              insecure: true
              bindDN: cn=admin,dc=opencloud,dc=eu
              user:
                userNameMatch: none
                schema:
                  id: openCloudUUID
              group:
                schema:
                  id: openCloudUUID
          appsIntegration:
            enabled: true
            wopiIntegration:
              officeSuites:
                - name: Collabora
                  product: Collabora
                  enabled: true
                  uri: "https://collabora.opencloud.test"
                  insecure: true
                  disableProof: false
                  iconURI: https://collabora.opencloud.test/favicon.ico
                  ingress:
                    enabled: false
                    domain: wopi.opencloud.test
                    ingressClassName: nginx
                    annotations:
                      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
                    tls:
                      - secretName: oc-dev-tls
                        hosts:
                          - wopi-collabora.kube.opencloud.test
                - name: OnlyOffice
                  product: OnlyOffice
                  enabled: false
                  uri: "https://onlyoffice.opencloud.test"
                  insecure: true
                  disableProof: false
                  iconURI: https://onlyoffice.opencloud.test/web-apps/apps/documenteditor/main/resources/img/favicon.ico
                  ingress:
                    enabled: false
      - services:
          nats:
            persistence:
              enabled: true
              size: "10Gi"
          search:
            persistence:
              enabled: true
              size: "10Gi"
            extractor:
              type: tika
          storagesystem:
            persistence:
              enabled: true
              size: "5Gi"
          storageusers:
            persistence:
              enabled: true
              size: "50Gi"
            storageBackend:
              driver: decomposeds3
 
          thumbnails:
            persistence:
              enabled: true
              size: "10Gi"
          web:
            persistence:
              enabled: true
              size: "1Gi"
            config:
              oidc:
                webClientID: web
              externalApps:
                external-sites:
                  config:
                    sites:
                      - name: openCloud
                        url: https://www.opencloud.eu
                        target: external
                        color: "#0D856F"
                        icon: cloud
                        priority: 50
            additionalInitContainers:
              - name: external-sites
                image: opencloudeu/web-extensions:external-sites-latest
                command:
                  - /bin/sh
                  - -c
                  - cp -R /usr/share/nginx/html/external-sites /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
              - name: drawio
                image: opencloudeu/web-extensions:draw-io-latest
                command:
                  - /bin/sh
                  - -c
                  - cp -R /usr/share/nginx/html/draw-io /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
              - name: importer
                image: opencloudeu/web-extensions:importer-latest
                command:
                  - /bin/sh
                  - -c
                  - cp -R /usr/share/nginx/html/importer /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
              - name: jsonviewer
                image: opencloudeu/web-extensions:json-viewer-latest
                command:
                  - /bin/sh
                  - -c
                  - cp -R /usr/share/nginx/html/json-viewer /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
              - name: progressbars
                image: opencloudeu/web-extensions:progress-bars-latest
                command:
                  - /bin/sh
                  - -c
                  - cp -R /usr/share/nginx/html/progress-bars /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
              - name: unzip
                image: opencloudeu/web-extensions:unzip-latest
                command:
                  - /bin/sh
                  - -c
                  - cp -R /usr/share/nginx/html/unzip /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
          idm:
            persistence:
              enabled: false
              size: "10Gi"
          ocm:
            persistence:
              enabled: false
              size: "1Gi"
      - extraResources:
          - |
            apiVersion: v1
            kind: Secret
            metadata:
              name: ldap-bind-secrets
            stringData:
              reva-ldap-bind-password: admin
            ---          
            apiVersion: v1
            kind: Secret
            metadata:
              name: s3secret
            stringData:
              accessKey: opencloud
              secretKey: opencloud-secret-key

  # --- OpenLDAP Release ---
  # Deploys the OpenLDAP stack for user and group management.
  - name: openldap
    namespace: openldap
    chart: openldap/openldap-stack-ha
    version: 4.3.3
    labels:
      ci-lint-skip: true # Skip linting this chart in CI, as it's an external dependency.
    values:
      - ltb-passwd:
          enabled: false # Disable password management tool if not needed.
      - replication:
          enabled: false # Enable replication for high availability.
      - replicaCount: 1 
      - global:
          ldapDomain: "opencloud.eu" # Set the base LDAP domain.
          # TODO: Change both adminPassword and configPassword to strong, secure values.
          adminPassword: admin
          configPassword: config
      - customLdifFiles:
          set_logging.ldif: |-
            dn: cn=config
            changetype: modify
            replace: olcLogLevel
            olcLogLevel: stats sync
          opencloud_root.ldif: |-
            dn: dc=opencloud,dc=eu
            objectClass: organization
            objectClass: dcObject
            dc: opencloud
            o: openCloud

            dn: ou=users,dc=opencloud,dc=eu
            objectClass: organizationalUnit
            ou: users

            dn: cn=admin,dc=opencloud,dc=eu
            objectClass: inetOrgPerson
            objectClass: person
            cn: admin
            sn: admin
            uid: ldapadmin

            dn: ou=groups,dc=opencloud,dc=eu
            objectClass: organizationalUnit
            ou: groups

            dn: ou=custom,ou=groups,dc=opencloud,dc=eu
            objectClass: organizationalUnit
            ou: custom
          users.ldif: |-

          groups.ldif: |-
            dn: cn=users,ou=groups,dc=opencloud,dc=eu
            objectClass: groupOfNames
            objectClass: top
            cn: users
            description: Users
            member: uid=alan,ou=users,dc=opencloud,dc=eu
            member: uid=mary,ou=users,dc=opencloud,dc=eu
            member: uid=margaret,ou=users,dc=opencloud,dc=eu
            member: uid=dennis,ou=users,dc=opencloud,dc=eu
            member: uid=lynn,ou=users,dc=opencloud,dc=eu
            member: uid=admin,ou=users,dc=opencloud,dc=eu

            dn: cn=chess-lovers,ou=groups,dc=opencloud,dc=eu
            objectClass: groupOfNames
            objectClass: top
            cn: chess-lovers
            description: Chess lovers
            member: uid=alan,ou=users,dc=opencloud,dc=eu

            dn: cn=machine-lovers,ou=groups,dc=opencloud,dc=eu
            objectClass: groupOfNames
            objectClass: top
            cn: machine-lovers
            description: Machine Lovers
            member: uid=alan,ou=users,dc=opencloud,dc=eu

            dn: cn=bible-readers,ou=groups,dc=opencloud,dc=eu
            objectClass: groupOfNames
            objectClass: top
            cn: bible-readers
            description: Bible readers
            member: uid=mary,ou=users,dc=opencloud,dc=eu

            dn: cn=apollos,ou=groups,dc=opencloud,dc=eu
            objectClass: groupOfNames
            objectClass: top
            cn: apollos
            description: Contributors to the Appollo mission
            member: uid=margaret,ou=users,dc=opencloud,dc=eu

            dn: cn=unix-lovers,ou=groups,dc=opencloud,dc=eu
            objectClass: groupOfNames
            objectClass: top
            cn: unix-lovers
            description: Unix lovers
            member: uid=dennis,ou=users,dc=opencloud,dc=eu

            dn: cn=basic-haters,ou=groups,dc=opencloud,dc=eu
            objectClass: groupOfNames
            objectClass: top
            cn: basic-haters
            description: Haters of the Basic programming language
            member: uid=dennis,ou=users,dc=opencloud,dc=eu

            dn: cn=vlsi-lovers,ou=groups,dc=opencloud,dc=eu
            objectClass: groupOfNames
            objectClass: top
            cn: vlsi-lovers
            description: Lovers of VLSI microchip design
            member: uid=lynn,ou=users,dc=opencloud,dc=eu

            dn: cn=programmers,ou=groups,dc=opencloud,dc=eu
            objectClass: groupOfNames
            objectClass: top
            cn: programmers
            description: Computer Programmers
            member: uid=alan,ou=users,dc=opencloud,dc=eu
            member: uid=margaret,ou=users,dc=opencloud,dc=eu
            member: uid=dennis,ou=users,dc=opencloud,dc=eu
            member: uid=lynn,ou=users,dc=opencloud,dc=eu

      - customSchemaFiles:
          10_opencloud_schema.ldif: |-
            # This LDIF files describes the OpenCloud schema
            dn: cn=opencloud,cn=schema,cn=config
            objectClass: olcSchemaConfig
            cn: opencloud
            olcObjectIdentifier: openCloudOid 1.3.6.1.4.1.63016
            # We'll use openCloudOid:1 subarc for LDAP related stuff
            #   openCloudOid:1.1 for AttributeTypes and openCloudOid:1.2 for ObjectClasses
            olcAttributeTypes: ( openCloudOid:1.1.1 NAME 'openCloudUUID'
              DESC 'A non-reassignable and persistent account ID)'
              EQUALITY uuidMatch
              SUBSTR caseIgnoreSubstringsMatch
              SYNTAX 1.3.6.1.1.16.1 SINGLE-VALUE )
            olcAttributeTypes: ( openCloudOid:1.1.2 NAME 'openCloudExternalIdentity'
              DESC 'A triple separated by "$" representing the objectIdentity resource type of the Graph API ( signInType $ issuer $ issuerAssignedId )'
              EQUALITY caseIgnoreMatch
              SUBSTR caseIgnoreSubstringsMatch
              SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
            olcAttributeTypes: ( openCloudOid:1.1.3 NAME 'openCloudUserEnabled'
              DESC 'A boolean value indicating if the user is enabled'
              EQUALITY booleanMatch
              SYNTAX 1.3.6.1.4.1.1466.115.121.1.7 SINGLE-VALUE)
            olcAttributeTypes: ( openCloudOid:1.1.4 NAME 'openCloudUserType'
              DESC 'User type (e.g. Member or Guest)'
              EQUALITY caseIgnoreMatch
              SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE )
            olcAttributeTypes: ( openCloudOid:1.1.5 NAME 'openCloudLastSignInTimestamp'
              DESC 'The timestamp of the last sign-in'
              EQUALITY generalizedTimeMatch
              ORDERING generalizedTimeOrderingMatch
              SYNTAX  1.3.6.1.4.1.1466.115.121.1.24 SINGLE-VALUE )
            olcObjectClasses: ( openCloudOid:1.2.1 NAME 'openCloudObject'
              DESC 'OpenCloud base objectclass'
              AUXILIARY
              MAY ( openCloudUUID ) )
            olcObjectClasses: ( openCloudOid:1.2.2 NAME 'openCloudUser'
              DESC 'OpenCloud User objectclass'
              SUP openCloudObject
              AUXILIARY
              MAY ( openCloudExternalIdentity $ openCloudUserEnabled $ openCloudUserType $ openCloudLastSignInTimestamp) )<environment_details>
