apiVersion: v2
name: opencloud
description: OpenCloud Helm community chart
keywords:
  - opencloud
  - owncloud
  - ocis
maintainers:
  - name: OpenCloud EU
    email: info@opencloud.eu
    url: https://opencloud.eu
type: application
version: 0.1.6
# renovate: datasource=docker depName=opencloudeu/opencloud-rolling
appVersion: latest
kubeVersion: ""
sources:
  - https://github.com/opencloud-eu/opencloud
  - https://github.com/owncloud/ocis
  - https://github.com/cs3org/reva
