{{- if and .Values.ingress.enabled .Values.ingress.ingressClassName "traefik" }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: add-x-forwarded-proto-https
  namespace: {{ include "opencloud.namespace" . }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
{{- end}}