{{- if and .Values.keycloak.enabled .Values.keycloak.internal.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud.keycloak.fullname" . }}-realm
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
data:
  opencloud-realm.json: {{ tpl (.Files.Get "files/keycloak/opencloud-realm.json.gotmpl") . | quote }}
{{- end }}
