apiVersion: batch/v1
kind: Job
metadata:
  name: opencloud-init
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: opencloud
        image: "{{ .Values.image }}:{{ .Values.tag}}"
        env:
        - name: IDM_ADMIN_PASSWORD
          value: {{ .Values.adminPassword }}
        - name: OC_INSECURE
          value: "{{ .Values.insecure }}"
        volumeMounts:
        - name: opencloud-config
          mountPath: /etc/opencloud
        - name: opencloud-data
          mountPath: /var/lib/opencloud
        # command: ["/usr/bin/opencloud"]
        args: ["init"]
      volumes:
        - name: opencloud-config
          persistentVolumeClaim:
            claimName: opencloud-config-pvc
        - name: opencloud-data
          persistentVolumeClaim:
            claimName: opencloud-data-pvc
      restartPolicy: Never
