apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencloud
  labels:
    app: opencloud  
spec:
  selector:
    matchLabels:
      app: opencloud
  replicas: 1
  template:
    metadata:
      labels:
        app: opencloud
    spec:
      containers:
      - name: opencloud
        image: "{{ .Values.image }}:{{ .Values.tag}}"
        env:
        - name: OC_INSECURE
          value: "{{ .Values.insecure }}"
        - name: PROXY_HTTP_ADDR
          value: "{{ .Values.proxyHttpAddr }}"
        - name: OC_URL
          value: "{{ .Values.url }}"
        volumeMounts:
          - name: opencloud-config
            mountPath: /etc/opencloud
          - name: opencloud-data
            mountPath: /var/lib/opencloud                  
      volumes:
        - name: opencloud-config
          persistentVolumeClaim:
            claimName: opencloud-config-pvc
        - name: opencloud-data
          persistentVolumeClaim:
            claimName: opencloud-data-pvc
